#!/bin/bash

for b in `git branch |grep -v '^*' |grep -v master` ; do
    git worktree add bldtree $b 
    echo Building $b ...
    docker rmi $b
    docker build -t $b bldtree > ${b}.log
    echo Finished
    git worktree remove bldtree
    echo ==================================
done

