#!/bin/bash

git clone `git remote -v |grep origin |grep fetch |awk '{print $2}'` bldtree

if [ ${1}. == '.' ] ; then
    br=`git branch -v |grep -v '^*' |grep -v master`
else
    br=$1
fi

(cd bldtree
for b in $br ; do
    echo Building $b ...
    git checkout $b
    docker rmi $b
    docker build -t $b . |tee ../${b}.log
    echo Finished
    echo ==================================
done
)

rm -rf bldtree

